// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef GAME_REST_H
#define GAME_REST_H

#include <ngrest/common/Service.h>

struct user_info_resp {
    std::string user_name;
    std::string user_logo;
    int user_cash;
    int table_no;
};

struct add_cash_req {
    std::string ssid;
    int cash;
};

struct table_created_resp {
    std::string created;
    int table_no;
};

struct qq_login_req {
    std::string openid;
    std::string acctok;
};


//! Dummy description for the service
/*! Some detailed description of the service */
// '*location' comment sets resource path for this service
// *location: game_rest
class game_rest: public ngrest::Service
{
public:
    // Here is an example of service operation
    //! Dummy description for the operation
    /*! Some detailed description of the operation */
    // To invoke this operation from browser open: http://localhost:9098/game_rest/World!
    //
    // '*location' metacomment sets path to operation relative to service operation.
    // Default value is operation name.
    // This will bind "echo" method to resource path: http://host:port/game_rest/{text}
    // *location: /{text}
    //
    // '*method' metacomment sets HTTP method for the operation. GET is default method.
    // *method: GET
    //
    std::string echo(const std::string& text);

    // *location: /wechat_login
    // *method: POST
    std::string proc_wechat_login(const std::string code);
    // *location: /qq_login
    // *method: POST
    std::string proc_qq_login(const qq_login_req& text);
    // *location: /userinfo/{ssid}
    // *method: GET
    user_info_resp proc_get_user_info(const std::string ssid);
    // *location: /logoff/{ssid}
    // *method: GET
    std::string proc_logoff(const std::string ssid);

    // *method: POST
    // *location: /add_cash
    std::string proc_add_cash(const add_cash_req& text);

    // *location: /create_table
    // *method: GET
    table_created_resp proc_create_table();
    // *location: /random_login
    // *method: GET
    std::string proc_random_login();
};


#endif // GAME_REST_H



