// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "game_rest.h"
#include "../../../public.h"

std::string game_rest::echo(const std::string& text)
{
    return "Hi, " + game_api_user_login("5555");
}


std::string game_rest::proc_login(const std::string code)
{
    return game_api_user_login(code);
}